# Generated by Django 4.2 on 2023-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('cnum', models.IntegerField(blank=True)),
                ('edate', models.DateField()),
                ('cvv', models.IntegerField(blank=True)),
            ],
        ),
    ]
