# Generated by Django 4.2 on 2023-07-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='edate',
            field=models.DateField(blank=True),
        ),
    ]
